using System.Text;

namespace Wikidown.Core;

// Exports the wiki's NavTree as Jekyll site data so a Liquid layout can
// render a left-nav tree that honors .order — Jekyll itself can't read
// .order files, and GitHub Pages' built-in builder can't run custom plugins.
public static class JekyllNavigation
{
    public const string DataFile = "_data/navigation.yml";

    public static string DataPath(WikiRepository repo) =>
        Path.Combine(repo.RootPath, "_data", "navigation.yml");

    public static bool IsEnabled(WikiRepository repo) => File.Exists(DataPath(repo));

    // Called by WikiRepository after every structural change, so a wiki that
    // opted in (via `wikidown pages`) never ships a stale sidebar.
    public static void RefreshIfEnabled(WikiRepository repo)
    {
        if (IsEnabled(repo)) Write(repo);
    }

    public static void Write(WikiRepository repo)
    {
        var path = DataPath(repo);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Render(repo));
    }

    public static string Render(WikiRepository repo)
    {
        var exclusions = PublishExclusions.Load(repo.RootPath);
        var pages = repo.Walk().Where(p => !PublishExclusions.IsExcluded(p, exclusions)).ToList();
        var tree = NavTree.Build(pages, repo.ReadOrder);
        var sb = new StringBuilder();
        sb.Append("# Generated by `wikidown pages` from the wiki's .order files — do not edit.\n");
        sb.Append("# Regenerated automatically whenever the wiki changes through the CLI or MCP server.\n");
        if (tree.Count == 0) sb.Append("[]\n");
        else RenderNodes(tree, sb, indent: 0);
        return sb.ToString();
    }

    private static void RenderNodes(IReadOnlyList<NavNode> nodes, StringBuilder sb, int indent)
    {
        var pad = new string(' ', indent);
        foreach (var node in nodes)
        {
            sb.Append(pad).Append("- title: ").Append(Quote(node.Title)).Append('\n');
            if (node.IsPage)
                sb.Append(pad).Append("  url: ").Append(Quote(node.Url)).Append('\n');
            if (node.Children.Count > 0)
            {
                sb.Append(pad).Append("  prefix: ").Append(Quote(node.Path.ToLinkPath() + "/")).Append('\n');
                sb.Append(pad).Append("  children:\n");
                RenderNodes(node.Children, sb, indent + 4);
            }
        }
    }

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
